name: Flak-Hobby
description: 'Flak-Hobby je specijalizovana prodavnica hobisticke proizvode, prvenstveno razne vrste plasticnih maketa i hemije.'
notif: "Od 13.10.2021. pa nadalje, radnja Flak Hobby će raditi i subotom od 11-16h.<br>Radnja Flak Hobby imaće štand na Novogodišnjem kupu 11. i 12. decembra u Muzeju Vazduhoplovstva na aerodromu Nikola Tesla.
Tamo ćete moći da kupite stvari iz čitavog asortimana sa popustom od 10%.
Odmah je moguće poslati rezervacije na naš mejl ili putem telefona za makete, hemiju i alat, koje biste preuzeli na kupu.
Vidimo se!"
