name: Flak-Hobby
description: 'Flak-Hobby je specijalizovana prodavnica hobisticke proizvode, prvenstveno razne vrste plasticnih maketa i hemije.'
notif: "U toku je poručivanje maketa, hemije, alata i ostalih maketarskih dodataka.
Mogu se poručiti makete svih brendova koje imamo u ponudi u radnji Flak Hobby: Eduard, Kinetic, GreatWallHobby, Tamiya, RFM, Takom, Hasegawa, Trumpeter, HobbyBoss itd.
Porudžbine primamo do 5. septembra. Upit za cene i dostupnost maketa možete poslati ovde putem facebooka, na mejl flakhobby@gmail.com ili nas možete pozvati na telefone 0646140177 ili 0641129145."
