name: Flak-Hobby
description: 'Flak-Hobby je specijalizovana prodavnica hobisticke proizvode, prvenstveno razne vrste plasticnih maketa i hemije.'
notif: "PORUČIVANJE U TOKU - Naručivanje maketa,hemije i alata traje do 16. avgusta, a roba se očekuje početkom septembra.
Za narudžbine me možete kontaktirati mejlom, telefonom ili preko fejsbuk stranice. Roba se doplaćuje kada stigne!
NOVO - MOGUĆE PORUČITI - Makete FineMolds, Bronco Models i veliki asortiman maketa ICM.
Trenutno NIJE moguće poručiti samo makete sledećih proizvođača - Tamiya, Trumpeter, HobbyBoss i MiniArt"
