name: Flak-Hobby
description: 'Flak-Hobby je specijalizovana prodavnica hobisticke proizvode, prvenstveno razne vrste plasticnih maketa i hemije.'
notif: "U toku je poručivanje maketa, hemije, alata i ostalih maketarskih dodataka.
Mogu se poručiti makete svih brendova koje imamo u ponudi u radnji Flak Hobby: Eduard, Kinetic, GreatWallHobby, Tamiya, RFM, Takom, Hasegawa, Trumpeter, Hobby Boss itd.
Moguće je poručiti i dodatke za diorame proizvođača ModelScene i Noch.
Porudžbine primamo do 30. decembra. <br>Upit za cene i dostupnost maketa možete poslati na mejl flakhobby@gmail.com ili nas možete pozvati na telefone 0646140177 ili 0641129145."
