name: Flak-Hobby
description: 'Flak-Hobby je specijalizovana prodavnica hobisticke proizvode, prvenstveno razne vrste plasticnih maketa i hemije.'
notif: "Radnja Flak Hobby je od sada u novom, većem lokalu broj 102, koji se takođe nalazi u sklopu tržnog centra Banjica. Lokal je na prvom spratu, od pokretnih stepenica levo do kraja hodnika (prekoputa starog lokala).
Zbog praznika, radnja neće raditi od 30.04.21 - 04.05.21.
<br>
Srećni praznici!"
