name: Flak-Hobby
description: 'Flak-Hobby je specijalizovana prodavnica hobisticke proizvode, prvenstveno razne vrste plasticnih maketa i hemije.'
notif: "Od danas počinje poručivanje maketa, hemije i alata svih proizvođača koje imamo u ponudi  (osim Trumpeter, Hobby Boss i Aoshima maketa).
Porudžbine za Eduard primamo do 7. novembra i moguće je poručiti novembarske novitete. 
Porudžbine za sve drugo primamo do 15. novembra. Za porudžbinu, možete poslati upit na mejl, fejsbuk stranicu ili me možete pozvati telefonom.
Novo u ponudi - DRAGON, TAMIYA i QUINTA STUDIO 3D Dekali
Lokal neće raditi od 10.11 – 14.11.2020, ali online poručivanje i slanje robe je i dalje moguće.
Uz dogovor (poželjno bar dan ranije) možete preuzeti robu u lokalu svim danima osim 11.11.2020.

Srdačno,
Vaš FlakHobby
"
