name: Flak-Hobby
description: 'Flak-Hobby je specijalizovana prodavnica hobisticke proizvode, prvenstveno razne vrste plasticnih maketa i hemije.'
notif: "U toku je poručivanje maketa, hemije, alata i ostalih potrebština! 
Moguće je poručiti od svih brendova koje već imamo u ponudi, a od sada su dostupni i neki novi:
<br>
MAKETE:
<br>
Special Hobby 
IBG
Flyhawk
Clear Prop
<br>
DODACI:
<br>
Master - metalne cevi (topovi, mitraljezi, pito i ostale cevi)
Reskit - rezinski dodaci
Quinta Studio - 3D Dekali
Uschi Van Der Rosten - dekali, šabloni, itd
Flyhawk - dodaci za brodove
<br>
DIORAME:
<br>
ModelScene - statične trave, podloge, žbunje, drveće itd.
<br>
Poručivanje traje do 25.05.2021. Upit za cene i dostupnost možete
poslati na mejl flakhobby@gmail.com ili me možete pozvati na telefone +381646140177, +381641129145."
