name: Flak-Hobby
description: 'Flak-Hobby je specijalizovana prodavnica hobisticke proizvode, prvenstveno razne vrste plasticnih maketa i hemije.'
notif: "Radnja nece raditi 10.3.(sreda) i 11.3.(cetvrtak) Vaš FlakHobby"
