name: Flak-Hobby
description: 'Flak-Hobby je specijalizovana prodavnica hobisticke proizvode, prvenstveno razne vrste plasticnih maketa i hemije.'
notif: "Poštovani kupci,
<br>
Od 1. maja Flak Hobby radnja menja lokaciju.
Novi lokal, broj 102 (prekoputa starog lokala), takođe se nalazi u sklopu TPC Banjica, Paunova 24. U pitanju je prvi sprat, levo do kraja hodnika od pokretnih stepenica.
<br>
Vidimo se!"
