name: Flak-Hobby
description: 'Flak-Hobby je specijalizovana prodavnica hobisticke proizvode, prvenstveno razne vrste plasticnih maketa i hemije.'
notif: "Radnja Flak Hobby neće raditi u subotu 18.12.2021. zbog priprema za slavu. 
<br>Vidimo se od ponedeljka!"
