name: Flak-Hobby
description: 'Flak-Hobby je specijalizovana prodavnica hobisticke proizvode, prvenstveno razne vrste plasticnih maketa i hemije.'
notif: "U toku je poručivanje Eduardovih septembarskih noviteta, kao i ostalih maketa i dodataka.
Rezervacije primamo do 6. septembra, a roba se očekuje oko 20. septembra.
Za cene me kontaktirajte putem mejla flakhobby@gmail.com"
