name: Flak-Hobby
description: 'Flak-Hobby je specijalizovana prodavnica hobisticke proizvode, prvenstveno razne vrste plasticnih maketa i hemije.'
notif: "NOVO NA STANJU - čitav asortiman Real Colors boja, Xtreme Metal boja, AK vodenih drvenih bojica kao i određena količina Hasegawa maketa."
