name: Flak-Hobby
description: 'Flak-Hobby je specijalizovana prodavnica hobisticke proizvode, prvenstveno razne vrste plasticnih maketa i hemije.'
notif: "U sredu i četvrtak 28.10. i 29.10. radnja će biti zatvorena zbog popisa."
