name: Flak-Hobby
description: 'Flak-Hobby je specijalizovana prodavnica hobisticke proizvode, prvenstveno razne vrste plasticnih maketa i hemije.'
notif: "Radnja Flak Hobby radiće normalno u četvrtak 11.11.2021.<br>Od 13.10.2021. pa nadalje, radnja Flak Hobby će raditi i subotom od 11-16h."
