name: Flak-Hobby
description: 'Flak-Hobby je specijalizovana prodavnica hobisticke proizvode, prvenstveno razne vrste plasticnih maketa i hemije.'
notif: "Od danas počinje poručivanje maketa, hemije i alata svih proizvođača koje imamo u ponudi  (osim Trumpeter, Hobby Boss i Aoshima maketa).
Porudžbine za Eduard primamo do 7. novembra i moguće je poručiti novembarske novitete. 
Porudžbine za sve drugo primamo do 15. novembra. Za porudžbinu, možete poslati upit na mejl, fejsbuk stranicu ili me možete pozvati telefonom.
Novo u ponudi - DRAGON, TAMIYA i QUINTA STUDIO 3D Dekali"
