name: Flak-Hobby
description: 'Flak-Hobby je specijalizovana prodavnica hobisticke proizvode, prvenstveno razne vrste plasticnih maketa i hemije.'
notif: " Lokal neće raditi od 10.11 – 22.11.2020, ali online poručivanje i slanje robe je i dalje moguće.
Uz dogovor (poželjno bar dan ranije) možete preuzeti robu u lokalu svim danima osim 11.11.2020.
<br>
Srdačno,
<br>
Vaš FlakHobby "
