name: Flak-Hobby
description: 'Flak-Hobby je specijalizovana prodavnica hobisticke proizvode, prvenstveno razne vrste plasticnih maketa i hemije.'
notif: "U toku je poručivanje maketa, hemije, alata i ostalih potrepština! Moguće je poručiti od svih brendova koje već imamo u ponudi, a od sada su dostupni i neki novi:
<br>
MAKETE: Airfix, Heller, Kittyhawk, Panda Hobby, MeritMicromir, Modelsvit, MirageHobby, Special Hobby, Revell, Roden, Kondor i Unimodels i još mnogo manjih proizvođača.
<br>
REZINSKI DODACI: Aires, Aerobonus, CMK, Quickboost, Wheeliant, Plus Model.
<br>
Dobavljač je obnovio lagere: Trumpeter, Hobby Boss, MiniArt, Meng, Takom, Kinetic, AFV Club tako da je ogromna većina maketa iz asortimana dostupna za poručivanje.
<br>
Poručene makete bi stigle u sredinom jula.
<br>
Po običaju upit za cene i dostupnost možete poslati putem fejsbuka, mejla flakhobby@gmail.com ili nas pozvati na telefon 0646140177."
