name: Flak-Hobby
description: 'Flak-Hobby je specijalizovana prodavnica hobisticke proizvode, prvenstveno razne vrste plasticnih maketa i hemije.'
notif: "U toku je poručivanje maketa, hemije, časopisa, knjiga, alata itd. svih proizvođača iz ponude (sem Trumpeter, HobbyBoss i MiniArt). Porudžbine primamo do 20.02.2021.
Upit za cenu i rezervaciju možete poslati na mejl flakhobby@gmail.com ili na telefon <a href=\"tel:\"0641129145>0641129145</a>.
<br>
Očekuje se da poručena roba stigne do sredine marta.
<br>
Vaš FlakHobby"
