name: Flak-Hobby
description: 'Flak-Hobby je specijalizovana prodavnica hobisticke proizvode, prvenstveno razne vrste plasticnih maketa i hemije.'
notif: "Novo (privremeno) skraćeno radno vreme radnje Flak Hobby 12h-17h
<br>
<p class=\"is-main-txt\">Stigao je potpuni asortiman akrilnih <a href=\"https://www.flakhobby.com/Boje_AMMO.html\">AMMO MiG</a> boja</p>
<br>
Srdačno,
<br>
Vaš FlakHobby "
