name: Flak-Hobby
description: 'Flak-Hobby je specijalizovana prodavnica hobisticke proizvode, prvenstveno razne vrste plasticnih maketa i hemije.'
notif: "Poštovani kupci,
U toku je poručivanje Trumpter, Hobby Boss, MiniArt, ICM, Meng i Takom maketa.
Porudžbine primamo do 15.04.2021. a roba se očekuje početkom maja.
Upite za cene i dostupnost možete poslati putem mejla ili me pozvati na mobilni telefon."
