name: Flak-Hobby
description: 'Flak-Hobby je specijalizovana prodavnica hobisticke proizvode, prvenstveno razne vrste plasticnih maketa i hemije.'
notif: "Stigla je dopuna AK boja, hemije, alata i časopisa, kao  i makete firmi ICM, Tamiya, Hasegawa, Meng i drugi."
