name: Flak-Hobby
description: 'Flak-Hobby je specijalizovana prodavnica hobisticke proizvode, prvenstveno razne vrste plasticnih maketa i hemije.'
notif: "Stigla je dopuna boja, hemije i alata AMMO MiG, kao i makete firmi Arma Hobby, Hobby 2000, Takom, RFM, Das Werk, Kinetic i Zoukei Mura"
