name: Flak-Hobby
description: 'Flak-Hobby je specijalizovana prodavnica hobisticke proizvode, prvenstveno razne vrste plasticnih maketa i hemije.'
notif: "Obnovljen je asortiman AMMO MiG  akrilnih boja AMMO MiG i hemije.
Nove makete koje su stigle, možete videti u kategoriji NOVO." 
