name: Flak-Hobby
description: 'Flak-Hobby je specijalizovana prodavnica hobisticke proizvode, prvenstveno razne vrste plasticnih maketa i hemije.'
notif: "Do 7. juna primamo porudžbine za Hasegawa i ModelSvit makete. Isporuka se očekuje krajem juna.
Hasegawa i ModelSvit makete su privremeno dostupne za poručivanje i pored ograničenog lagera koji stigne, neće više biti dostupne u kontekstu poručivanja."
