name: Flak-Hobby
description: 'Flak-Hobby je specijalizovana prodavnica hobisticke proizvode, prvenstveno razne vrste plasticnih maketa i hemije.'
notif: "Poštovani kupci, Flak Hobby će od 15.03.2021 - 22.03.2021. raditi samo ONLINE.
Moguće je poručiti artikle dostupne na sajtu i biće poslati PostExpress-om ili drugim kurirom po izboru.
Do kraja nedelje stižu nove makete, kao i dopune boja, hemije i alata.<br>Hvala na razumevanju,
<br>Vaš FlakHobby"
