name: Flak-Hobby
description: 'Flak-Hobby je specijalizovana prodavnica hobisticke proizvode, prvenstveno razne vrste plasticnih maketa i hemije.'
notif: "Drage mušterije, lokal neće raditi tokom standardnog radnog vremena do daljnjeg imajući u vidu trenutnu situaciju sa korona virusom. Online poručivanje i slanje robe PostExpress-om je i dalje moguće. Takođe se možemo dogovoriti putem mejla ili telefonom (uz najavu bar dan ranije) da robu preuzmete u lokalu, radnim danima - pon-pet.
<br>
Srdačno,
<br>
Vaš FlakHobby "
