name: Flak-Hobby
description: 'Flak-Hobby je specijalizovana prodavnica hobisticke proizvode, prvenstveno razne vrste plasticnih maketa i hemije.'
notif: "Radnja neće raditi od 31.12.2020. do 03.01.2022."
