---
---

backend:
  name: github
  repo: stevannestorovic/bojiste

media_folder: "assets/img"


collections:
  - name: "site-info"
    label: "Site info"
    files:
      - label: "Site settings" 
        name: "site"
        file: "_data/site.yml"
        fields: 
          - name: "name"
            label: "Shop name"
            widget: "string"
      - label: "Contact page"
        name: "contact"
        file: "_data/contact.yml"
        fields:
          - name: "address"
            label: "Address"
            widget: "string"
          - name: "tel"
            label: "Phone number"
            widget: "string"
          - name: "email"
            label: "Email"
            widget: "string"
          - name: "map_link"
            label: "Map link"
            widget: "string"
      
  - name: "product"
    label: "Product"
    folder: "_products/"
    create: true
    identifier_field: name
    fields:
      - {label: "Product name", name: "title", widget: "string"}
      - {label: "Product price", name: "price", widget: "string"}
      - {label: "Product description", name: "desc", widget: "string"}
      - {label: "Image", name: "img_path", widget: "image"}

      - {name: "cat",
        label: "Category",
        widget: "select",
        options: [
        {%- for cat in site.data.cats -%}
	        {% if site.data.cats.last.maincat == cat.maincat %}
	          {label: "{{cat.maincat}}", value: "{{cat.maincat}}"}
	        {% else %}
	          {label: "{{cat.maincat}}", value: "{{cat.maincat}}"},
          {% endif %}
	      {%- endfor -%}],
	      default: "{{site.data.cats.first.maincat}}"}
      
      - {name: "subcat",
        label: "Sub Category",
        widget: "select",
        options: [
	      {% assign lastsubcat = site.data.cats.last.subcats.last %}
        {%- for cat in site.data.cats -%}
          {% assign cname = cat.maincat %}
          {%- for subcat in cat.subcats-%}
            {%if lastsubcat == subcat %}
              {label: "{{cname}}->{{subcat.name}}", value: "{{subcat.name}}"}
	          {% else %}
              {label: "{{cname}}->{{subcat.name}}", value: "{{subcat.name}}"},
	          {% endif %}
          {%- endfor -%}
	      {%- endfor -%}],
	      default: "{{site.data.cats.first.maincat.subcats.first.name}}"}

      - {name: "subsubcat",
        label: "Sub Sub Category",
        widget: "select",
        options: [
	      {% assign lsscname = site.data.cats.last.subcats.last.subsubcats.last.name %}
	      {% assign lsscparent = site.data.cats.last.subcats.last.name %}
	      {% assign lsscgrandparent = site.data.cats.last %}
        {%- for cat in site.data.cats -%}
          {% assign cname = cat.maincat %}
          {%- for subcat in cat.subcats-%}
            {% assign sname = subcat.name %}
            {%- for subsubcat in subcat.subsubcats -%}
              {%if lsscname == subsubcat  and lsscparent == sname and lsscgrandparent == cname %}
                {label: "{{cname}}->{{sname}}->{{subsubcat}}", value: "{{subsubcat}}"}
	            {% else %}
                {label: "{{cname}}->{{sname}}->{{subsubcat}}", value: "{{subsubcat}}"},
	            {% endif %}
	          {%- endfor -%}
            {%- endfor -%}
	      {%- endfor -%}],
	      default: "{{site.data.cats.first.maincat.subcats.first.name}}"}

