---
---

backend:
  name: github
  repo: stevavoliajvar/bojiste

media_folder: "assets/img"


collections:
  - name: "shop-info"
    label: "Shop info"
    files:
      - label: "Shop settings" 
        name: "site"
        file: "_data/site.yml"
        fields: 
          - name: "name"
            label: "Shop name"
            widget: "string"
          - name: "description"
            label: "Shop Description"
            widget: "text"
      - label: "Contact page"
        name: "contact"
        file: "_data/contact.yml"
        fields:
          - name: "address"
            label: "Address"
            widget: "string"
          - name: "tel"
            label: "Phone number"
            widget: "string"
          - name: "email"
            label: "Email"
            widget: "string"
          - name: "map_link"
            label: "Map link"
            widget: "string"
  - name: "brand"
    label: "Brand"
    folder: "_brands/"
    create: true
    identifier_field: name
    fields:
      - {label: "layout", name: "layout", default: "brand", widget: "hidden"}
      - {label: "Brand name", name: "name", widget: "string"}
      - {label: "Brand label", name: "label", widget: "string"}
      - {label: "Brand image", name: "img", widget: "image" }
      - {label: "Description", name: "body", widget: "markdown"}
  - name: "product"
    label: "Product"
    folder: "_products/"
    create: true
    identifier_field: name
    fields:
      - {label: "layout", name: "layout", default: "product", widget: "hidden"}
      - {label: "Product name", name: "title", widget: "string"}
      - {label: "Product price", name: "price", widget: "string"}
      - {label: "Productt code", name: "sifra", widget: "string"}
      - {label: "Product description", name: "desc", widget: "string"}
      - {label: "Image", name: "img_path", widget: "image", required: false}
      - {label: "Brand", 
         name: "brand", 
         widget: "select", 
         options: [
         {%- for brand in site.brands -%}
	        {% if site.brands.last.name == brand.name %}
	            {label: "{{brand.name}}", value: "{{brand.name}}"}
	          {% else %}
	            {label: "{{brand.name}}", value: "{{brand.name}}"},
            {% endif %}
	        {%- endfor -%}   
         ],
         default: "Choose brand"}
      - {label: "Available", name: "available", widget: "boolean", default: true}
      - {label: "Special offer", name: "special_offer", widget: "boolean", default: false}
      - {label: "Soon", name: "soon", widget: "boolean", default: false}
      - {name: "cat",
        label: "Category",
        widget: "select",
        options: [
        {%- for cat in site.data.cats -%}
	        {% if site.data.cats.last.maincat == cat.maincat %}
	          {label: "{{cat.maincat.name}}", value: "{{cat.maincat.label}}"}
	        {% else %}
	          {label: "{{cat.maincat.name}}", value: "{{cat.maincat.label}}"},
          {% endif %}
	      {%- endfor -%}],
	      default: "{{site.data.cats.first.maincat.name}}",
        required: false}
      
      - {name: "subcat",
        label: "Sub Category",
        widget: "select",
        options: [
	      {% assign lastsubcat = site.data.cats.last.subcats.last %}
        {%- for cat in site.data.cats -%}
          {% assign cname = cat.maincat.name %}
          {%- for subcat in cat.subcats-%}
            {%if lastsubcat == subcat %}
              {label: "{{cname}}->{{subcat.name}}", value: "{{subcat.label}}"}
	          {% else %}
              {label: "{{cname}}->{{subcat.name}}", value: "{{subcat.label}}"},
	          {% endif %}
          {%- endfor -%}
	      {%- endfor -%}],
	      default: "{{site.data.cats.first.maincat.subcats.first.name}}",
        required: false}

      - {name: "subsubcat",
        label: "Sub Sub Category",
        widget: "select",
        options: [
	      {% assign lsscname = site.data.cats.last.subcats.last.subsubcats.last.name %}
	      {% assign lsscparent = site.data.cats.last.subcats.last.name %}
	      {% assign lsscgrandparent = site.data.cats.last %}
        {%- for cat in site.data.cats -%}
          {% assign cname = cat.maincat.name %}
          {%- for subcat in cat.subcats -%}
            {% assign sname = subcat.name %}
            {%- for subsubcat in subcat.subsubcats -%}
	      {% assign ssname = subsubcat.name %}
              {%if lsscname == ssname  and lsscparent == sname and lsscgrandparent == cname %}
                {label: "{{cname}}->{{sname}}->{{ssname}}", value: "{{subsubcat.label}}"}
	            {% else %}
                {label: "{{cname}}->{{sname}}->{{ssname}}", value: "{{subsubcat.label}}"},
	            {% endif %}
	          {%- endfor -%}
            {%- endfor -%}
	      {%- endfor -%}],
	      default: "",
        required: false}

