backend:
  name: github
  repo: stevannestorovic/bojiste

media_folder: "assets/img"


collections:
  - name: "site-info"
    label: "Site info"
    files:
      - label: "Site settings" 
        name: "site"
        file: "_data/site.yml"
        fields: 
          - name: "name"
            label: "Shop name"
            widget: "string"
      - label: "Contact page"
        name: "contact"
        file: "_data/contact.yml"
        fields:
          - name: "address"
            label: "Address"
            widget: "string"
          - name: "tel"
            label: "Phone number"
            widget: "string"
          - name: "email"
            label: "Email"
            widget: "string"
          - name: "map_link"
            label: "Map link"
            widget: "string"
      
  - name: "product"
    label: "Product"
    folder: "_products/"
    create: true
    identifier_field: name
    fields:
      - {label: "Product name", name: "title", widget: "string"}
      - {label: "Product price", name: "price", widget: "string"}
      - {label: "Product description", name: "desc", widget: "string"}
      - {label: "Image", name: "img_path", widget: "image"}
      - name: "category"
        label: "Category"
        widget: "select"
        options: 
          - {label: "Boja", value: "boja"}
          - {label: "Maketa", value: "maketa"}
        default: "boja"
      - name: "brand"
        label: "Brand"
        widget: "select"
        options: 
          - {label: "mig", value: "mig"}
          - {label: "IMT", value: "imt"}
