---
---

backend:
  name: github
  repo: stevannestorovic/bojiste

media_folder: "assets/img"


collections:
  - name: "site-info"
    label: "Site info"
    files:
      - label: "Site settings" 
        name: "site"
        file: "_data/site.yml"
        fields: 
          - name: "name"
            label: "Shop name"
            widget: "string"
      - label: "Contact page"
        name: "contact"
        file: "_data/contact.yml"
        fields:
          - name: "address"
            label: "Address"
            widget: "string"
          - name: "tel"
            label: "Phone number"
            widget: "string"
          - name: "email"
            label: "Email"
            widget: "string"
          - name: "map_link"
            label: "Map link"
            widget: "string"
      
  - name: "product"
    label: "Product"
    folder: "_products/"
    create: true
    identifier_field: name
    fields:
      - {label: "Product name", name: "title", widget: "string"}
      - {label: "Product price", name: "price", widget: "string"}
      - {label: "Product description", name: "desc", widget: "string"}
      - {label: "Image", name: "img_path", widget: "image"}
      - name: "category"
        label: "Category"
        widget: "select"
        options: [ 
         {%- for category in site.data.categories -%}
         {% if site.data.categories.last == category%}
	  {label: "{{category.label}}", value: "{{category.name}}"}
	 {% else %}
	  {label: "{{category.label}}", value: "{{category.name}}"},
	 {% endif %}
	 {%- endfor -%}]
        default: "{{ site.data.categories.first.name }}"
      - name: "brand"
        label: "Brand"
        widget: "select"
        options: [ 
         {%- for brand in site.data.brands -%}
         {% if site.data.brands.last == brand %}
	  {label: "{{brand.label}}", value: "{{brand.name}}"}
	 {% else %}
	  {label: "{{brand.label}}", value: "{{brand.name}}"},
	 {% endif %}
	 {%- endfor -%}]
        default: "{{ site.data.brands.first.name }}"
